[package]
name = "makepad-site"
authors = ["John Gildred <274078+jgildred@users.noreply.github.com>"]
description = "Static website template using Makepad"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
spin-sdk = "3.0.1"
