spin_manifest_version = 2

[application]
name = "makepad-site"
version = "0.1.0"
authors = ["John Gildred <274078+jgildred@users.noreply.github.com>"]
description = "Static website template using Makepad"

[[trigger.http]]
route = "/api/..."
component = "makepad-site"

[component.makepad-site]
source = "target/wasm32-wasi/release/makepad_site.wasm"
allowed_outbound_hosts = []

[component.makepad-site.build]
command = "./build-frontend.sh"
watch = ["src/**/*.rs", "frontend/src/**/*.rs", "Cargo.toml", "frontend/Cargo.toml"]

[[trigger.http]]
route = "/..."
component = "static-server"

[component.static-server]
source = "static-server/spin_static_fs.wasm"
files = [{ source = "webroot", destination = "/" }]
