spin_manifest_version = 2

[application]
name = "makepad-site"
version = "0.1.0"
authors = ["John Gildred <274078+jgildred@users.noreply.github.com>"]
description = "Static website template using Makepad"

[component.makepad-site]
source = "target/wasm32-wasi/release/makepad_site.wasm"
allowed_outbound_hosts = []

[component.makepad-site.build]
command = "./build-frontend.sh\ncargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "makepad-site-frontend/src/**/*.rs", "Cargo.toml", "spin.toml", "makepad-site-frontend/Cargo.toml"]

[[trigger.http]]
route = "/api/..."
component = "makepad-site"

[[trigger.http]]
route = "/r/..."
component = "makepad-site"

[[trigger.http]]
route = "/..."
component = "static-server"

# [[trigger.http]]
# route = "/index.html"
# component = "static-server"

# [[trigger.http]]
# route = "/makepad-site-frontend.wasm"
# component = "static-server"

# [[trigger.http]]
# route = "/makepad_platform/..."
# component = "static-server"

# [[trigger.http]]
# route = "/makepad_site_frontend/..."
# component = "static-server"

# [[trigger.http]]
# route = "/makepad_wasm_bridge/..."
# component = "static-server"

# [[trigger.http]]
# route = "/makepad_widgets/..."
# component = "static-server"

[component.static-server]
source = "static-server/spin_static_fs.wasm"
files = [{ source = "webroot", destination = "/" }]